AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM_Policy_Change_Alarm"
Resources:
  EventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "detect-iam-policy-changes"
      Description: "A CloudWatch Event Rule that detects IAM policy changes and publishes change events to an SNS topic for notification. Events include IAM policy creation/deletion/update operations as well as attaching/detaching policies from IAM users, roles or groups."
      State: "ENABLED"
      Targets:
        - Arn:
            Ref: "SnsTopicEventRule"
          Id: "target-id1"
      EventPattern:
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "iam.amazonaws.com"
          eventName:
            - "DeleteRolePolicy"
            - "DeleteUserPolicy"
            - "PutGroupPolicy"
            - "PutRolePolicy"
            - "PutUserPolicy"
            - "CreatePolicy"
            - "DeletePolicy"
            - "CreatePolicyVersion"
            - "DeletePolicyVersion"
            - "AttachRolePolicy"
            - "DetachRolePolicy"
            - "AttachUserPolicy"
            - "DetachUserPolicy"
            - "AttachGroupPolicy"
            - "DetachGroupPolicy"
            - "DeleteGroupPolicy"
  SnsTopicEventRule:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: IAM-USER-POLICY-CHANGE-ALARM
      KmsMasterKeyId: alias/iam-policy-change/root-usage-alarm
      Subscription:
        - Endpoint: "awsprime@conversadocs.com"
          Protocol: "email"
      TopicName: "IAM_Policy_Change_Alarm"
  SnsTopicPolicyEventRule:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Sid: "__default_statement_ID"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "SNS:GetTopicAttributes"
              - "SNS:SetTopicAttributes"
              - "SNS:AddPermission"
              - "SNS:RemovePermission"
              - "SNS:DeleteTopic"
              - "SNS:Subscribe"
              - "SNS:ListSubscriptionsByTopic"
              - "SNS:Publish"
              - "SNS:Receive"
            Resource:
              Ref: "SnsTopicEventRule"
            Condition:
              StringEquals:
                AWS:SourceOwner:
                  Ref: "AWS::AccountId"
          - Sid: "TrustCWEToPublishEventsToMyTopic"
            Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource:
              Ref: "SnsTopicEventRule"
      Topics:
        - Ref: "SnsTopicEventRule"
Parameters: {}
Metadata: {}
Conditions: {}
